### ISSUE TITLE
ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /

### ISSUE THREAD

**Issue by uiosun** [g-plane/pnpm-docker#2]
When I use "gplane/pnpm:7.14.2-node16-alpine" (or 7.14.1 other same)

Running the Docker Image directly results is: `ERR_PNPM_NO_PKG_MANIFEST No package.json found in /`

How to fix this error? My project need 7.14.* PNPM, please.

**Comment by g-plane** [comment]
You should run pnpm in your project directory.

**Comment by uiosun** [comment]
I got it, sorry about my docker knowledge is leak.

Thanks for you, the work is better!
